// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/securitycenter/v1/finding.proto

package com.google.cloud.securitycenter.v1;

public final class FindingOuterClass {
  private FindingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_securitycenter_v1_Finding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_securitycenter_v1_Finding_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_securitycenter_v1_Finding_SourcePropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_securitycenter_v1_Finding_SourcePropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_securitycenter_v1_Finding_ExternalSystemsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_securitycenter_v1_Finding_ExternalSystemsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,google/cloud/securitycenter/v1/finding" +
      ".proto\022\036google.cloud.securitycenter.v1\032\037" +
      "google/api/field_behavior.proto\032\031google/" +
      "api/resource.proto\032+google/cloud/securit" +
      "ycenter/v1/access.proto\0324google/cloud/se" +
      "curitycenter/v1/external_system.proto\0320g" +
      "oogle/cloud/securitycenter/v1/iam_bindin" +
      "g.proto\032.google/cloud/securitycenter/v1/" +
      "indicator.proto\0321google/cloud/securityce" +
      "nter/v1/mitre_attack.proto\0323google/cloud" +
      "/securitycenter/v1/security_marks.proto\032" +
      "2google/cloud/securitycenter/v1/vulnerab" +
      "ility.proto\032\034google/protobuf/struct.prot" +
      "o\032\037google/protobuf/timestamp.proto\"\357\016\n\007F" +
      "inding\022\014\n\004name\030\001 \001(\t\022\016\n\006parent\030\002 \001(\t\022\025\n\r" +
      "resource_name\030\003 \001(\t\022<\n\005state\030\004 \001(\0162-.goo" +
      "gle.cloud.securitycenter.v1.Finding.Stat" +
      "e\022\020\n\010category\030\005 \001(\t\022\024\n\014external_uri\030\006 \001(" +
      "\t\022X\n\021source_properties\030\007 \003(\0132=.google.cl" +
      "oud.securitycenter.v1.Finding.SourceProp" +
      "ertiesEntry\022J\n\016security_marks\030\010 \001(\0132-.go" +
      "ogle.cloud.securitycenter.v1.SecurityMar" +
      "ksB\003\340A\003\022.\n\nevent_time\030\t \001(\0132\032.google.pro" +
      "tobuf.Timestamp\022/\n\013create_time\030\n \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022B\n\010severity\030\014 \001" +
      "(\01620.google.cloud.securitycenter.v1.Find" +
      "ing.Severity\022\026\n\016canonical_name\030\016 \001(\t\022:\n\004" +
      "mute\030\017 \001(\0162,.google.cloud.securitycenter" +
      ".v1.Finding.Mute\022K\n\rfinding_class\030\021 \001(\0162" +
      "4.google.cloud.securitycenter.v1.Finding" +
      ".FindingClass\022<\n\tindicator\030\022 \001(\0132).googl" +
      "e.cloud.securitycenter.v1.Indicator\022D\n\rv" +
      "ulnerability\030\024 \001(\0132-.google.cloud.securi" +
      "tycenter.v1.Vulnerability\0229\n\020mute_update" +
      "_time\030\025 \001(\0132\032.google.protobuf.TimestampB" +
      "\003\340A\003\022[\n\020external_systems\030\026 \003(\0132<.google." +
      "cloud.securitycenter.v1.Finding.External" +
      "SystemsEntryB\003\340A\003\022A\n\014mitre_attack\030\031 \001(\0132" +
      "+.google.cloud.securitycenter.v1.MitreAt" +
      "tack\0226\n\006access\030\032 \001(\0132&.google.cloud.secu" +
      "ritycenter.v1.Access\022\026\n\016mute_initiator\030\034" +
      " \001(\t\022@\n\014iam_bindings\030\' \003(\0132*.google.clou" +
      "d.securitycenter.v1.IamBinding\032O\n\025Source" +
      "PropertiesEntry\022\013\n\003key\030\001 \001(\t\022%\n\005value\030\002 " +
      "\001(\0132\026.google.protobuf.Value:\0028\001\032f\n\024Exter" +
      "nalSystemsEntry\022\013\n\003key\030\001 \001(\t\022=\n\005value\030\002 " +
      "\001(\0132..google.cloud.securitycenter.v1.Ext" +
      "ernalSystem:\0028\001\"8\n\005State\022\025\n\021STATE_UNSPEC" +
      "IFIED\020\000\022\n\n\006ACTIVE\020\001\022\014\n\010INACTIVE\020\002\"Q\n\010Sev" +
      "erity\022\030\n\024SEVERITY_UNSPECIFIED\020\000\022\014\n\010CRITI" +
      "CAL\020\001\022\010\n\004HIGH\020\002\022\n\n\006MEDIUM\020\003\022\007\n\003LOW\020\004\"C\n\004" +
      "Mute\022\024\n\020MUTE_UNSPECIFIED\020\000\022\t\n\005MUTED\020\001\022\013\n" +
      "\007UNMUTED\020\002\022\r\n\tUNDEFINED\020\004\"\202\001\n\014FindingCla" +
      "ss\022\035\n\031FINDING_CLASS_UNSPECIFIED\020\000\022\n\n\006THR" +
      "EAT\020\001\022\021\n\rVULNERABILITY\020\002\022\024\n\020MISCONFIGURA" +
      "TION\020\003\022\017\n\013OBSERVATION\020\004\022\r\n\tSCC_ERROR\020\005:\333" +
      "\001\352A\327\001\n%securitycenter.googleapis.com/Fin" +
      "ding\022@organizations/{organization}/sourc" +
      "es/{source}/findings/{finding}\0224folders/" +
      "{folder}/sources/{source}/findings/{find" +
      "ing}\0226projects/{project}/sources/{source" +
      "}/findings/{finding}B\332\001\n\"com.google.clou" +
      "d.securitycenter.v1P\001ZLgoogle.golang.org" +
      "/genproto/googleapis/cloud/securitycente" +
      "r/v1;securitycenter\252\002\036Google.Cloud.Secur" +
      "ityCenter.V1\312\002\036Google\\Cloud\\SecurityCent" +
      "er\\V1\352\002!Google::Cloud::SecurityCenter::V" +
      "1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.api.ResourceProto.getDescriptor(),
          com.google.cloud.securitycenter.v1.AccessProto.getDescriptor(),
          com.google.cloud.securitycenter.v1.ExternalSystemProto.getDescriptor(),
          com.google.cloud.securitycenter.v1.IamBindingProto.getDescriptor(),
          com.google.cloud.securitycenter.v1.IndicatorProto.getDescriptor(),
          com.google.cloud.securitycenter.v1.MitreAttackProto.getDescriptor(),
          com.google.cloud.securitycenter.v1.SecurityMarksOuterClass.getDescriptor(),
          com.google.cloud.securitycenter.v1.VulnerabilityProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_google_cloud_securitycenter_v1_Finding_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_securitycenter_v1_Finding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_securitycenter_v1_Finding_descriptor,
        new java.lang.String[] { "Name", "Parent", "ResourceName", "State", "Category", "ExternalUri", "SourceProperties", "SecurityMarks", "EventTime", "CreateTime", "Severity", "CanonicalName", "Mute", "FindingClass", "Indicator", "Vulnerability", "MuteUpdateTime", "ExternalSystems", "MitreAttack", "Access", "MuteInitiator", "IamBindings", });
    internal_static_google_cloud_securitycenter_v1_Finding_SourcePropertiesEntry_descriptor =
      internal_static_google_cloud_securitycenter_v1_Finding_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_securitycenter_v1_Finding_SourcePropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_securitycenter_v1_Finding_SourcePropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_cloud_securitycenter_v1_Finding_ExternalSystemsEntry_descriptor =
      internal_static_google_cloud_securitycenter_v1_Finding_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_securitycenter_v1_Finding_ExternalSystemsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_securitycenter_v1_Finding_ExternalSystemsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.securitycenter.v1.AccessProto.getDescriptor();
    com.google.cloud.securitycenter.v1.ExternalSystemProto.getDescriptor();
    com.google.cloud.securitycenter.v1.IamBindingProto.getDescriptor();
    com.google.cloud.securitycenter.v1.IndicatorProto.getDescriptor();
    com.google.cloud.securitycenter.v1.MitreAttackProto.getDescriptor();
    com.google.cloud.securitycenter.v1.SecurityMarksOuterClass.getDescriptor();
    com.google.cloud.securitycenter.v1.VulnerabilityProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
